# Sources :
#     https://openclassrooms.com/fr/courses/2035766-optimisez-votre-deploiement-en-creant-des-conteneurs-avec-docker/6211677-creez-un-fichier-docker-compose-pour-orchestrer-vos-conteneurs
#     https://www.youtube.com/watch?v=kIqWxjDj4IU&ab_channel=AndrewSchmelyun
#     https://github.com/SavchenkoDV/inception_School21_Ecole42/blob/master/srcs/docker-compose.yml
#     https://www.youtube.com/watch?v=786dRn1Ioug&t=2s&ab_channel=Korben

version: '2.7'

networks:
  localhost:
    name: inception_network

volumes:
  wp:
    name: wordpress
    driver: local
    driver_opts:
      device: /mnt/c/Users/nicol/OneDrive/Bureau/coding/projets/inception/srcs/data_wp
      o: bind
      type: none
  db:
    name: db
    driver: local
    driver_opts:
      device: /mnt/c/Users/nicol/OneDrive/Bureau/coding/projets/inception/srcs/data_db
      o: bind
      type: none

services:

  nginx:
    build:  ./requirements/nginx/
    image:  nginx_img
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/wordpress
    networks:
      - localhost
    restart: always

  mariadb:
    build:  ./requirements/mariadb/
    image:  db_image
    container_name: db
    networks:
      - localhost
    restart: always
    volumes:
      - db:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build:  ./requirements/wordpress
    image:  wordpress_image
    container_name:  wordpress
    networks:
      - localhost
    volumes:
      - wp:/var/www/wordpress
    restart: always