version: '3'

volumes:
  db_volume: {}

services:

  mariadb:
    build: ./requirements/mariadb/
    image: db_image
    container_name: db
    restart: always
    volumes:
      - db_volume:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=test
